name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/MojTest
            git pull
            cd frontend
            npm install
            npm run build
            sudo cp -r dist/* /var/www/mojtest/
            sudo nginx -t
            sudo systemctl reload nginx
            cd ..
            ./mvnw clean package -DskipTests
            sudo systemctl restart mojtest