name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/MojTest
            git pull origin main
            cd frontend
            npm install
            npm run build
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S cp -r dist/* /var/www/mojtest/  # Changed path
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S chown -R www-data:www-data /var/www/mojtest
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S chmod -R 755 /var/www/mojtest
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S nginx -t
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl reload nginx
            cd ..
            ./mvnw clean package -DskipTests
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart mojtest